---
variables:
  GIT_DEPTH: 2

include:
  - project: 'accelerator-controls/environment/ci'
    ref: master # a22f89f2e751508cad42734cecd04783e40b468f # (GIT SHA) # v1.0.0 (GIT TAG) # master (GIT BRANCH)
    file: 'setEnvALSU.yml'
  - project: accelerator-controls/environment/ci
    ref: master
    file: 'debian12-epics.yml'
  - project: accelerator-controls/environment/ci
    ref: master
    file: 'rocky8-epics.yml'
  - project: accelerator-controls/environment/ci
    ref: master
    file: 'rocky9-epics.yml'

stages:
  - build
  - test

debian12-builder:
  script:
    - echo "Running tests... "
    - bash test.bash

rock8-builder:
  script:
    - echo "Running tests... "
    - bash test.bash

rock9-builder:
  script:
    - echo "Running tests... "
    - bash test.bash

