Alpine:
    image: alpine
    stage: test
    before_script:
    - apk update
    - apk --no-cache add bash git shellcheck
    script:
    - git ls-files --exclude='*.bash' --ignored | xargs shellcheck

CentOS:
    image: centos:7.9.2009
    stage: test
    before_script:
    - yum -y update
    - yum -y install epel-release && yum repolist
    - yum -y update
    - yum -y install bash git ShellCheck
    script:
    - git ls-files --exclude='*.bash' --ignored | xargs shellcheck

Debian:
    image: debian:buster-slim
    stage: test
    before_script:
    - apt update
    - apt install -y install bash git shellcheck
    script:
    - git ls-files --exclude='*.bash' --ignored | xargs shellcheck

