build-centos7:
    stage: build
    tags:
        - centos7-epics
    
    script:
        - source /usr/local/setEnv
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"
        - caget -h

build-debian10:
    stage: build
    tags:
        - debian10-epics

    script:
        - source /usr/local/setEnv
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"
        - caget -h

build-rock8:
    stage: build
    tags:
        - rocky8-epics

    script:
        - source /usr/local/setEnv
        - caget -h
