
build-centos7:
    stage: build
    tags:
        - centos7-epics
    script:
        - shellcheck -v
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"

build-debian10:
    stage: build
    tags:
        - debian10-epics
        - shellcheck -v
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"
