build-centos7:
    stage: build
    tags:
        - centos7-epics
    
    script:
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"
        - tree /usr/local/epics
        - caget -h

build-debian10:
    stage: build
    tags:
        - debian10-epics

    script:
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"

build-rock8:
    stage: build
    tags:
        - rocky8-epics

    script:
        - tree /usr/local/epics
