include:
  - project: accelerator-controls/environment/ci
    file: setGenericEnv.yml
  - project: accelerator-controls/environment/ci
    file: debian12-epics.yml
  - project: accelerator-controls/environment/ci
    file: rocky9-epics.yml
  - project: accelerator-controls/environment/ci
    file: logbooks.yml

stages:
  - build
  - test
  - deploy
  
debian11-builder:
    script:
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found! or shellcheck error"

debian11-tester:
    script:
        - export USERNAME="gitlab"
        - bash ${CI_PROJECT_DIR}/test.bash

rocky9-builder:
    script:
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found! or shellcheck error"

rocky9-tester:
    script:
        - export USERNAME="gitlab"
        - bash ${CI_PROJECT_DIR}/test.bash
        
