include:
  - project: accelerator-controls/environment/ci
    file: setEnv.yml
  - project: accelerator-controls/environment/ci
    file: centos7-epics.yml
  - project: accelerator-controls/environment/ci
    file: debian10-epics.yml
  - project: accelerator-controls/environment/ci
    file: rocky8-epics.yml
  - project: accelerator-controls/environment/ci
    file: sl7-epics.yml

stages:
  - build
  - test

centos7-builder:
    script:
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"

centos7-tester:
    script:
        - export USERNAME="gitlab"
        - bash ${CI_PROJECT_DIR}/test.bash

debian10-builder:
    script:
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"

debian10-tester:
    script:
        - export USERNAME="gitlab"
        - bash ${CI_PROJECT_DIR}/test.bash


rocky8-tester:
    script:
        - export USERNAME="gitlab"
        - bash ${CI_PROJECT_DIR}/test.bash
        
sl7-builder:
    script:
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck || echo "No script found!"
        