include:
  - project: alsu/ci
    file: setEnv-template.yml

build-centos7:
    stage: build
    tags:
        - centos7-epics
    
    script:
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"

test-centos7:
    stage: test
    needs: [ "build-centos7" ]
    tags:
        - centos7-epics
    script:
        - export USERNAME="gitlab"
        - bash ${CI_PROJECT_DIR}/test.bash


build-debian10:
    stage: build
    tags:
        - debian10-epics
    script:
        - shellcheck -V
        - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"

test-debian10:
    stage: test
    needs: [ "build-debian10" ]
    tags:
        - debian10-epics
    script:
        - export USERNAME="gitlab"
        - bash ${CI_PROJECT_DIR}/test.bash

build-rocky8:
    stage: build
    tags:
        - rocky8-epics
    script:
        - run.sh pmd -h

test-rocky8:
    stage: test
    needs: [ "build-rocky8" ]
    tags:
        - rocky8-epics
    script:
        - export USERNAME="gitlab"
        - bash ${CI_PROJECT_DIR}/test.bash
        
