Alpine:
    image: alpine
    stage: test
    before_script:
    - apk update
    - apk --no-cache add bash git shellcheck
    - shellcheck -V
    script:
    - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"

#CentOS:
#    image: centos:7.9.2009
#    stage: test
#    before_script:
#    - yum -y install git bash sudo
#    - yum -y update
#    - git clone https://github.com/jeonghanlee/pkg_automation
#    - bash ${CI_PROJECT_DIR}/pkg_automation/pkg_automation.bash -y
#    - yum -y install ShellCheck
#    script:
#    - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!" 

#Debian:
#    image: debian:buster-slim
#    stage: test
#    before_script:
#    - apt update
#    - apt install -y bash git shellcheck
#    script:
#    - export SHELLCHECK_OPTS="-e SC1117"
#    - git ls-files --exclude='*.bash' --ignored | xargs shellcheck  || echo "No script found!"

